language: node_js
notifications:
  email:
    on_failure: always
node_js:
  - "8.10"
script:
  - npm run build
  - npm test
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master
after_success:
  - npx semantic-release
